### ISSUE TITLE
README: similar projects

### ISSUE THREAD

**Issue by novoid** [karlicoss/orger#1]
Hi,

https://github.com/novoid/Memacs is very similar to orger.

My README will feature a link to your project under "Similar Projects". You might also think of linking it back to Memacs and/or Memex (also mentioned in my README).

This way, people looking for a solution to their problem might find alternative projects that might match better their use-cases.

**Comment by karlicoss** [comment]
Hey, good suggestion; updated!

I only found out about Memacs after someone linked in a reddit post about Orger, and I deliberately didn't look at it deeply yet since I have one more post in drafts about Orger and didn't want to interfere the perspective by starting to look how Memacs is implemented. 

Once I publish that, I'll look in detail since I'm pretty sure we could benefit at the very least from sharing code to fetch data from the APIs (as Memacs seems to do) or parse it from existing export files (as Orger does).

**Comment by novoid** [comment]
Memacs is not API-centric per se. It is a framework that is here to make it easy for anybody to come up with a new module for a new data source. In this, its quite flexible.
